### PR TITLE
Fix: Take service priority into account when registering providers in…

### LINKED ISSUE #1101: Default provider overwrites custom provider service
Introduction of #1083 patch broke our production app!
One of our types uses a custom provider, but now after the changes the custom provider is overwritten by the default one!
$providers = $container->findTaggedServiceIds('fos_elastica.provider'); (RegisterProvidersPass line 31) finds the tagged services first, then the default ones, and then proceeds to overwrite them. There is no way to disable the default provider now, and our app is broken :(

### PR DESCRIPTION
**Pull request by GeoffroyR**
Fixes #1101

### CODE REVIEW

**Comment by XWB** [comment]
All tests have failed.

**Comment by XWB** [comment]
Thanks.

**Comment by WhatsOn** [comment]
Awesome, thanks!

**Comment by progrupa** [comment]
Is there a chance to have this in the 3.x branch as well?

**Pull request merged**
