### PR TITLE
Convert identifierValue to string if it is an object during deletion

### PR DESCRIPTION
**Pull request by spiroski**
This should address the problem of using a ValueObject as an ID. 
It will only convert the value to string if the value is object.

### CODE REVIEW

**Comment by spiroski** [comment]
Any feedback? 
I really need this, and is a a blocker for my app.

**Comment by spiroski** [comment]
More then a month, and no response at all...

**Comment by XWB** [comment]
I'm still not sure if this is the right solution. Implementation will fail if the object doesn't have a toString method.

**Comment by spiroski** [comment]
It will fail anyway if it is an object. 
This way at least if it can be casted to string it will work.

Also in most instances, if value objects are used for IDs, they will have toString method in order to work with them ( for generating urls, for storing in db, for serialization ).

**Comment by spiroski** [comment]
@XWB Any thoughts? 

I really need this, preparing to launch soon. 

This doesn't break backwards compatibility since if someone is using objects it would already be throwing an exception. There really isn't any real downside of merging this.

**Comment by XWB** [comment]
How about using the [PropertyAccess Component](http://symfony.com/doc/current/components/property_access.html)?

**Comment by spiroski** [comment]
How would you use it with the id? I have tried that months ago, but can't find anything that would work.

**Comment by Tobion** [comment]
Fixed in #1357

**Pull request closed without merging**
