### PR TITLE
Cast identifier to string in case it is an object

### PR DESCRIPTION
**Pull request by spiroski**
If the entity uses object that can be casted to string, the bundle should do that.

Re: @ #1156

### CODE REVIEW

**Comment by spiroski** [comment]
Can I have some kind of response regarding this issue? It has a big impact on my use-cases.

**Comment by XWB** [comment]
Thanks.

**Comment by XWB** [comment]
Reverting as this breaks as lot of tests.

**Comment by spiroski** [comment]
I don't think reverting this back is the correct decision.

Do you agree that it's expected behavior for this bundle to handle object identifiers that are castable to string?
Will you merge this feature back in if I manage to fix the test problems?

**Pull request merged**
