### PR TITLE
Enable use of hints when transforming results to entities

### PR DESCRIPTION
**Pull request by progrupa**
Useful when using extensions like translatable

### CODE REVIEW

**Comment by merk** [comment]
Thanks! This looks like a good start but I dont like the idea of adding hints as a concept for all elastica_to_model transformers because other backends do not support such a feature.

I would like to see an exception thrown if hints are configured for a backend that doesnt support them.

**Comment by progrupa** [comment]
Sure thing, there You go.

**Comment by merk** [comment]
Sorry, I should have been more specific - I'd prefer to see the validation occur in the Configuration class, not in the Extension. It can be done using this approach: http://symfony.com/doc/current/components/config/definition.html#validation-rules

**Comment by progrupa** [comment]
No problem, moved it to the Configuration class.

**Comment by merk** [comment]
Could you please add a cookbook entry that explains the use of hints with an example?

Thanks. Once thats done this should be ready to merge into 3.2-dev.

**Comment by progrupa** [comment]
Should it be included in an existing section, or would You rather have it in a separate cookbook entry?

**Comment by merk** [comment]
I think a separate cookbook entry makes more sense here.

**Comment by progrupa** [comment]
Added the cookbook entry.
Also, renamed the 'class' parameter to 'value', since query hints accept arbitrary values, not only class names like the Query::HINT_CUSTOM_TREE_WALKERS.

**Comment by XWB** [comment]
Thank you.

**Pull request merged**
