### PR TITLE
Made default sort options from pagination config to work as expected

### PR DESCRIPTION
**Pull request by dariuszz123**
Fallback to defaultSortFieldName and defaultSortDirection pagination options instead of ignoring then.

### CODE REVIEW

**Comment by XWB** [comment]
Thanks.

**Comment by robhunt3r** [comment]
We are getting errors like `Undefined index defaultSortFieldName` even when we do not sort our results. We are using KnpPaginatorBundle, but it was working few days ago, we just updated FosElastica so problem may be here.

**Comment by dariuszz123** [comment]
Lets revert this PR for now. I will inspect compatibility with KnpPaginatorBundle issues and create new PR.

**Comment by XWB** [comment]
@dariuszz123 Done https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/0f13ecc916f8f7dde92f371acfdfc6d7e3925933

**Pull request merged**
