### PR TITLE
[documentation]  Be a little bit verbose with aliases and setup

### PR DESCRIPTION
**Pull request by cbastienbaron**
change orders actions to avoid downtime and add some usefull informations

### CODE REVIEW

**Comment by XWB** [comment]
@cbastienbaron Can you fix the merge conflict?

**Comment by cbastienbaron** [comment]
@XWB hoo :) done

**Comment by cbastienbaron** [comment]
workflow tested in production like described in this PR, works like a charm ! :+1: 
Any reason to not merge ?

**Comment by XWB** [comment]
Thanks; no particular reason, just didn't find the time yet :)

**Comment by cbastienbaron** [comment]
:+1:  Ty @XWB

**Pull request merged**
