### PR TITLE
es 1.7 function_score is incomplete

### PR DESCRIPTION
**Pull request by Raffaello**
field value factor is missing in elastica until 2.3.1

### CODE REVIEW

**Comment by Raffaello** [comment]
anyone on this?

**Comment by merk** [comment]
There doesnt appear to be any relevant changes for this PR?

**Comment by Raffaello** [comment]
in the composer.json is not using the ruflin/elastica dependency that have the some functionality such as:
function_score query etc...

-        "ruflin/elastica": "~2.1,<2.3",
+        "ruflin/elastica": "~2.1,<2.3.*",

**Comment by Raffaello** [comment]
it means it is not possible to use with foselasticabundle this function:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

with some other parameters.

**Comment by XWB** [comment]
This is not the right way to resolve an issue, we should make it work on 2.3.1 too.

**Comment by Raffaello** [comment]
exactly, the issue is just the composer.json constrain on ruflin/elastica
that dsl are implemented in the 2.3.1 and actually fos/elastica bundle strictly express to use less than 2.3 of ruflin/elastica
@XWB the 2.3.1 is rufflin/elastica dependency not FOSElasticaBundle.
there is no reason why not to upgrade the ruflin/elastica in FOSElastica

**Pull request closed without merging**
