### PR TITLE
Support Symfony 7

### PR DESCRIPTION
**Pull request by endroid**
Add support for Symfony 7

### CODE REVIEW

**Comment by evertharmeling** [comment]
LGTM, probably #1931 should be merged first

**Comment by endroid** [comment]
Yes or merge them both and do a final fix if necessary.

**Comment by rusted-love** [comment]
@arghav @alanbem @xabbuh @ddeboer @merk
Where are the contributors with approval access?
Symfony 7 support is importnat update.

**Comment by xabbuh** [comment]
I don't have any merge access here

**Comment by XWB** [comment]
I'd be happy to merge if you fix the pipeline.

**Comment by endroid** [comment]
I see someone else has also started working on this in the meanwhile so I'm closing this one. No use in multiple people building the same thing :)

**Pull request closed without merging**
