### PR TITLE
Add params for AwsAuthV4 transport method

### PR DESCRIPTION
**Pull request by rairlie**
Elastica supports the AwsAuthV4 transport method as of ruflin/Elastica/pull/1056, however FOSElasticaBundle doesn't allow the parameters to be passed down to the client. This PR adds this.

Example configuration:

```
fos_elastica:
    clients:
        default:
            url: "http://my-aws-endpoint"
            transport: "AwsAuthV4"
            aws_access_key_id: "my-aws-access-key"
            aws_secret_access_key: "my-aws-secret-access-key"
            aws_region: "my-aws-region"
```

Fixes FriendsOfSymfony/FOSElasticaBundle/issues/1060

### CODE REVIEW

**Comment by XWB** [comment]
Can you update the test suite as well?

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Tests/DependencyInjection/ConfigurationTest.php

**Comment by rairlie** [comment]
Sure, now added.

**Comment by XWB** [comment]
Thanks.

**Comment by mauricoder** [comment]
Shouldn't this piece of information, on how to setup the Bundle to connect to AWS ElasticSearch authenticating with an IAM User, be part of the Bundle documentation? 

We struggled a lot to find this information. Maybe it's there but we didn't see it.

I refer to documentation here:

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/index.md

Thanks

**Pull request merged**
