### PR TITLE
setup per symfony version

### PR DESCRIPTION
**Pull request by sukhoy94**
I suggest to mark that there is no AppKernel.php in newest version of symfony, instead there is bundles.php

### CODE REVIEW

**Comment by XWB** [comment]
Or just rename the entry to `src/Kernel.php`.

**Comment by sukhoy94** [comment]
@XWB in newest Symfony bundles are included inside config/bundles.php, I think that should be mentioned in docs. Anyway when use flex bundle added automatically

**Comment by XWB** [comment]
That's true. As we don't support Symfony 3 anymore it would be better to remove the entire section.

**Comment by sukhoy94** [comment]
Okay, I've created new PR https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1851

**Pull request closed without merging**
