### PR TITLE
Update elastica lib

### PR DESCRIPTION
**Pull request by Gladhon**

### CODE REVIEW

**Comment by solivier** [comment]
Hi @Gladhon,

it seems it's not compatible php3 and accordind to the .travis it has to be compatible.

**Comment by Gladhon** [comment]
you're right. But php5.3 is no longer supported since 2014. Perhaps it can be dropped, symfony3 also dropped support for php5.3

**Comment by solivier** [comment]
Agree the same for the support of php5.4

**Comment by XWB** [comment]
Will be done in https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1069

**Pull request closed without merging**
