### PR TITLE
Support BackedEnums in ModelToElasticaAutoTransformer

### PR DESCRIPTION
**Pull request by b1rdex**

### CODE REVIEW

**Comment by b1rdex** [comment]
Hi @XWB! I fixed the issues and tests are passing now. Please review the code.

Code style check should be fixed with #1870 merge.

**Comment by XWB** [comment]
:+1: Can you rebase?

**Comment by b1rdex** [comment]
@XWB done

**Comment by XWB** [comment]
👍 Thank you.

**Pull request merged**
