### PR TITLE
Store fixed

### PR DESCRIPTION
**Pull request by mappedinn**
Hi, This PR fixes the bug of the issue #985  that adds for each property `"store": true`.

### CODE REVIEW

**Comment by mappedinn** [comment]
@merk, @richardmiller: can you have a look on this small fix?

**Comment by foaly-nr1** [comment]
+1

**Comment by foaly-nr1** [comment]
@mappedinn Reading @merk's comment on your initial bug report, I think he envisaged something different from this PR. I think the status property shouldn't automatically be added at all (because within ElasticSearch it defaults to true) and tests need to be added.

> Send a PR that removes store:true from MappingBuilder (since it is default it shouldnt be there unless false), provided there are added tests for the change I'm happy to merge it

**Comment by mappedinn** [comment]
@foaly-nr1 you are right. But, I proposed this PR as **quick fix** because the bundle does not work unless you correct MappingBuilder.

**Comment by merk** [comment]
Quick fixes do not get merged without tests.

I'll be pushing a commit shortly that removes setting store:true by default, which negates the need for this change.

**Comment by mappedinn** [comment]
thank you very much @merk

**Pull request closed without merging**
