### PR TITLE
Fixed Symfony 2.7 deprecated messages

### PR DESCRIPTION
**Pull request by XWB**

### CODE REVIEW

**Comment by cameronmurphy** [comment]
Thank you! This will save us 200 warnings every `composer install` :smile:

**Comment by XWB** [comment]
Perhaps @stof can have a look?

**Comment by stof** [comment]
looks good to me

**Comment by digitalkaoz** [comment]
awww thank you :)

**Comment by whisller** [comment]
Any news when it will be merged?

**Comment by XWB** [comment]
Ping @merk

**Comment by whisller** [comment]
Would be really good to have this merged.

**Comment by francisbesset** [comment]
@merk merge + tag please :)

**Comment by tgabi333** [comment]
+1

**Comment by stof** [comment]
@XWB I will let you handle the releasing (please don't forget to update changelog files though)

**Comment by stof** [comment]
and this will also need to be merged in newer branches

**Comment by XWB** [comment]
@stof Will do.

**Pull request merged**
