### PR TITLE
Use correct Doctrine registry

### PR DESCRIPTION
**Pull request by makasim**
fixes https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1369

Should be merged to 5.x too.

### CODE REVIEW

**Comment by franmomu** [comment]
Hi, it would be nice to merge it in 5.x soon because it doesn't work with mongodb right now.

**Comment by valimero** [comment]
You can put temporary “dev-master” in your composer.json !

**Comment by franmomu** [comment]
I know, thanks! I was a reminder, just in case :)

**Comment by jacquelotjeff** [comment]
Hello, 
I'm agree with franmomu, it's a real bug not an improvement ... 
It should be merge now in 5.x tags because many people are blocked (and using dev-master tag is not a good practice !)

Thanks.

**Pull request merged**
