### PR TITLE
Typo in manual-provider.md

### PR DESCRIPTION
**Pull request by CedCannes**
Typo in class path

### CODE REVIEW

**Comment by merk** [comment]
I dont believe this to be a typo. I recommend in this circumstance (of a application's UserBundle) to group classes relating to purpose, not their type. In this case I'd expect to put all FOSElasticaBundle custom classes under the Search\ namespace.

**Comment by CedCannes** [comment]
I agree with you.
I Thought that a typo mistake beacuse in service configuration we have : 
class: Acme\UserBundle\Search\UserProvider

and the namespace of the class UserProvider in example is : 
namespace Acme\UserBundle\Provider;

Search or Provider  ? :)

**Comment by merk** [comment]
You're right - thanks I completely missed the discrepancy :)

**Comment by merk** [comment]
Merged with `c4a2858` into 3.0.x

**Pull request closed without merging**
