### PR TITLE
[WIP] Add PersistingEvent and dispatch INSERT_OBJECTS event when populating

### PR DESCRIPTION
**Pull request by borNfreee**
Implementation for #887
This is a WIP PR. Just want to be on the same page with you @merk 
Please provide your feedback and I'll continue.

TODO:
- [x] create REPLACE_OBJECTS event and dispatch it in appropriate places
- [x] add unit tests for dispatched events
- [ ] update documentation

### CODE REVIEW

**Comment by merk** [comment]
I'd prefer to only dispatch in a single place - not having to trigger the same event in multiple places, otherwise I'm okay with the direction.

**Comment by borNfreee** [comment]
> I'd prefer to only dispatch in a single place - not having to trigger the same event in multiple places

What do you mean? There are at least 2 separate places with `->insertMany()` function  where this event should be dispatched (this is for populate command)
* for [Doctrine](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/a59f2015b49a1b9fc8906b39e724321fe45c9c91/Doctrine/AbstractProvider.php#L95)
* for [Propel](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/a59f2015b49a1b9fc8906b39e724321fe45c9c91/Propel/Provider.php#L32) 

And the same event should be dispatched when collection of objects [are inserted in the Listener](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/a59f2015b49a1b9fc8906b39e724321fe45c9c91/Doctrine/Listener.php#L147)

**Comment by merk** [comment]
Thats my point - Dispatching an event before calling insertMany() in 3 places doesnt make sense. The responsibilities of the services that make these calls are not for transformation.

Making the call in the insertMany() call is more appropriate, IMO. https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Persister/ObjectPersister.php#L118

**Comment by borNfreee** [comment]
> Making the call in the insertMany() call is more appropriate

Totally agree, it was [my initial thought](https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/887).
Updated code, added unit tests. Please review.

FYI: tests are failed and seems like this is because of newest symfony 2.7 deprecated messages.

**Comment by borNfreee** [comment]
ping @merk

**Comment by borNfreee** [comment]
ping again @merk

**Comment by borNfreee** [comment]
@merk could you please review this PR or close it if you think this is not something this bundle need?

**Comment by XWB** [comment]
@borNfreee I can merge this PR is if you can update it with master.

**Comment by XWB** [comment]
Closing this PR as nobody really needs it.

**Pull request closed without merging**
