### PR TITLE
change dispatch() calls to symfony 4.3 syntax

### PR DESCRIPTION
**Pull request by chypriote**
Following the discussion in #1537, I've updated the calls to dispatch().

### CODE REVIEW

**Comment by stloyd** [comment]
This is no-go in forcing new format of call as we have to support older versions (LTS) which don't support that way.

This can be done only if you add some proxy function that will check version of Symfony & then decide about format of call.

**Comment by chypriote** [comment]
That's the point of the LegacyEventDispatcherProxy as seen [in symfony's doc](https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching#supporting-both-dispatchers)

**Comment by XWB** [comment]
But the `LegacyEventDispatcherProxy` class does not exists in older Symfony versions.

**Comment by chypriote** [comment]
Oh yeah you are right

**Comment by yunosh** [comment]
Any plans to merge this PR?

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1592

**Pull request closed without merging**
