### PR TITLE
optimized travis.yml for faster builds

### PR DESCRIPTION
**Pull request by IonBazan**
This should significally decrease time spent on dependency installation by composer

### CODE REVIEW

**Comment by alekitto** [comment]
No code coverage is generated after this change. PHPUnit warns that `No code coverage driver is available`.
Probably the `xdebug.ini` readded with `config-add` is not containing `extension=xdebug.so`

**Comment by IonBazan** [comment]
You are right. I assumed that `phpenv config-rm` disables the config, but it actually removes it.

**Comment by alekitto** [comment]
@IonBazan You can try this solution: https://github.com/Shippable/support/issues/2140#issuecomment-165718472

**Comment by XWB** [comment]
Will close this, feel free to open a new PR.

**Pull request closed without merging**
