### PR TITLE
Symfony deprecations

### PR DESCRIPTION
**Pull request by biozshock**
This PR introduce:

* a new Event class that maintain BC to SF3.4
* dispatch method compliant to new method signature
* removed by travis dunglas/symfony-lock and added symfony/flex

finished what @giovannialbero1992 had started in #1613 , creds to him

### CODE REVIEW

**Comment by deguif** [comment]
Hi @biozshock 

This should be fixed by https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1569

**Comment by biozshock** [comment]
That PR will be certainly merged into next major release, while this patch provides fixes for the current major release. Hope it makes sense.

**Comment by XWB** [comment]
Now that https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1569 has been merged, can you check if this PR is still relevant?

**Comment by giovannialbero1992** [comment]
Now minimum Symfony packages version is 4.4 so I think is not more necessary to keep BC with previous versions.

**Comment by XWB** [comment]
:+1:

**Comment by biozshock** [comment]
Now I see why i had deprecation warnings. The #1592 is not in any of v5.1.x tags. May we have a new tag with recent 5.x branch then?

**Pull request closed without merging**
