### PR TITLE
Test on PHP 8.0

### PR DESCRIPTION
**Pull request by deguif**
- [x] PR on `ruflin/elastica` to add support for PHP 8.0 (See https://github.com/ruflin/Elastica/pull/1794)
- [x] PR on `elasticsearch/elasticsearch` to add support for PHP 8.0

### CODE REVIEW

**Comment by giovannialbero1992** [comment]
@deguif I opened a PR here https://github.com/elastic/elasticsearch-php/pull/1063 for elasticsearch-php

**Comment by deguif** [comment]
Nice, I didn't have time to do it ;)

**Comment by curry684** [comment]
As https://github.com/elastic/elasticsearch-php/pull/1063 was merged, when is FOSElastica going up?

**Comment by XWB** [comment]
I think @deguif will have to update this PR and test against PHP 8 to see if there are any errors.

**Comment by deguif** [comment]
Yes, this one was merged too: https://github.com/elastic/elasticsearch-php/pull/1075
I'm waiting an official release to update this PR ;)

**Comment by bogdandubyk** [comment]
any updates, when we can expect PHP8 support? :)

**Comment by deguif** [comment]
@bogdandubyk still no official release on https://github.com/elastic/elasticsearch-php for PHP 8.0 support which blocks https://github.com/ruflin/Elastica and this project.

**Comment by jleehr** [comment]
[elastic/elasticsearch-php](https://github.com/elastic/elasticsearch-php) gets PHP8 support for version 7.11, which will be released soon.
See [https://github.com/elastic/elasticsearch-php/issues/1083#issuecomment-773913570](https://github.com/elastic/elasticsearch-php/issues/1083#issuecomment-773913570)

**Comment by deguif** [comment]
I'm preparing official release on   [ruflin/elastica](https://github.com/ruflin/elastica) now that  [elastic/elasticsearch-php](https://github.com/elastic/elasticsearch-php) 7.11.0 was released.

**Comment by darthf1** [comment]
Hi @deguif is it possible to merge this and allow php 8?

**Pull request merged**
