### PR TITLE
simple fixing of the bug adding the property store:true

### PR DESCRIPTION
**Pull request by mappedinn**
Hi,

This PR fixes the bug of the issue #985  that adds for each property `"store": true` by simply commenting the code in charge of it in `Index/MappingBuilder.php`.

### CODE REVIEW

**Comment by merk** [comment]
I'll be pushing a commit shortly that removes setting store:true by default, which negates the need for this change.

**Comment by ngeleedst** [comment]
Is their any news about this fix. Because now i cannot populate because it's adding store: true to a type: object etc.. and this is not allowed!

            if (!isset($property['store']) && $property == 'string') {
                $property['store'] = true;
            }

**Comment by ngeleedst** [comment]
Or wait maybe just by adding:  $skipTypes = array('completion','nested','object'); 
Shall i do a pull request with the new type 'object' added to the skypTypes?

**Comment by ngeleedst** [comment]
I did a new pull request regarding this ticket. See: [https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1013](url)

**Pull request closed without merging**
