### PR TITLE
Add a reindex command to update index mapping without downtime

### PR DESCRIPTION
**Pull request by progrupa**
This pull request creates a ReindexCommand which allows to update index mapping without downtime.
It creates a new index, updates it's mappings, populates it with the content of the old index. Then it switches the alias used and updates changes made during the reindex process.
Only works with aliased indices.

### CODE REVIEW

**Comment by merk** [comment]
Can you please talk a bit more about why you copy the index to a new one? Are you using external tools to populate index data on top of Elastica/FOSElasticaBundle that you need to keep across new populations?

**Comment by merk** [comment]
Overall I think I like where this is headed. I'd like to see the copying of documents moved out into its own general service that only handles copying, and if you can fix up the CS of the pull (missing copyright headers at the top, PSR2 issues with some of the files, use PHPUnit standard method names).

I also noticed that I split out the logger closure stuff into its own service a few minutes ago but missed that you'd done that - sorry.

**Comment by progrupa** [comment]
Well, my use case is that I use ES as a standalone storage, therefore I need to be able to change index mapping information without losing data. I have no source to populate it from.

I'll work on the issues You've mentioned.

**Comment by merk** [comment]
What are you reindexing from then? Wouldn't it make more sense to have independent indexes for different data sources and search combined indexes?

**Comment by progrupa** [comment]
It depends on your use case.
For me, ElasticSearch is a primary data source, and this command allows me to modify index/type mappings without losing any data.

**Comment by merk** [comment]
I suggest you contribute functionality included here for copying data in indexes to the Elastica project because this requirement is not specific to FOSElasticaBundle and its users and may be useful for other people using Elastica that do not use symfony.

You can then leverage that capability in your own project to modify index/types without losing data. I'm not sure FOSElasticaBundle should have much responsibility here (you can use the services defined by the bundle once Elastica has the feature)

**Pull request closed without merging**
