### PR TITLE
Update usage.md for RepositoryManager

### PR DESCRIPTION
**Pull request by pDc-**
Fix the documentation with true values for the new RepositoryManager

### CODE REVIEW

**Comment by alekitto** [comment]
This example should be corrected too:

```php
/** var FOS\ElasticaBundle\Repository */
$repository = $repositoryManager->getRepository('UserBundle:User');
```

Requesting a repository via its entity class name is deprecated.
The new repository manager requires `index/type` to be passed to the `getRepository` method.

**Comment by lsmith77** [comment]
@alekitto could you create a separate PR for this?

**Comment by XWB** [comment]
Closing this outdated PR.

**Comment by pDc-** [comment]
@XWB Can you explain why is it outdated please ?

**Comment by XWB** [comment]
Well we should have this in the 4.x branch and according to the first comment, something else is missing.

**Comment by XWB** [comment]
You can off course create a new PR :)

**Comment by pDc-** [comment]
@XWB Tank you for your answer. :) I will create a new PR then.

**Pull request closed without merging**
