### PR TITLE
resolve symfony deprecations

### PR DESCRIPTION
**Pull request by giovannialbero1992**
This PR introduce:
 - a new Event class that maintain BC to SF3.4
 - dispatch method compliant to new method signature
 - removed by travis dunglas/symfony-lock and added symfony/flex

### CODE REVIEW

**Comment by tacman** [comment]
PHP 7.1 is no longer supported.  Can we remove it from Travis?  Perhaps this will pass then.

**Comment by giovannialbero1992** [comment]
For me is ok, but it should be clear that we drop compatibility with SF 3.4, the test fail because is installed sf3.4 and dispatch method is different

**Comment by franmomu** [comment]
The [5.x branch already supports Symfony 5](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/5.x/composer.json), but there is no release yet.

**Comment by gmorel** [comment]
Hi, thanks for your hard work.
Would it be possible to have a tag on 5.x ?

**Pull request closed without merging**
