### PR TITLE
Upgrade PHP CS Fixer

### PR DESCRIPTION
**Pull request by keradus**
Used v1 is not maintained for over a year.

I upgraded it to v2, keeping currently configured rules as-is.

there were some violations I fixed, most of the diff is result of applying requested in config `ordered_class_elements`. If you don't feel comfortable with it, let me know - I will revert last commit.

### CODE REVIEW

**Comment by XWB** [comment]
Looks good, but unit tests have failed.

**Comment by keradus** [comment]
I don't see unit tests failing anywhere. issue is composer conflict on sf components - shall v2.8 be still supported indeed ?

**Comment by XWB** [comment]
Thanks.

**Comment by keradus** [comment]
you welcome ;)
actually, my question is still valid ;)

**Comment by XWB** [comment]
I think we can keep s2.8 support as long as it doesn't require much effort.

**Comment by keradus** [comment]
Sadly, it blocks you from update other packages, and there is already Sf not only 3, but 4 as well.

**Pull request merged**
