### PR TITLE
Update Elastica dependency

### PR DESCRIPTION
**Pull request by XWB**

### CODE REVIEW

**Comment by mattjanssen** [comment]
We, too, would like to use Elastica 2.0 in order to use Elasticsearch 1.5.

From what I can tell, there are very few breaking changes: https://github.com/ruflin/Elastica/releases/tag/2.0.0

**Comment by merk** [comment]
The condition change is wrong here, we need to disallow 2.1-dev. I've released v3.1.4 and v3.0.10 with Elastica 2.0 allowed.

**Comment by mattjanssen** [comment]
:+1: @merk !

**Comment by XWB** [comment]
:+1:

**Pull request closed without merging**
