### PR TITLE
Don't use parent identifier for objects/nested documents

### LINKED ISSUE #357: Custom identifier on nested object
As of now i can be able to specify custom identifier of the main document, but when it comes to nested objects where the nested object has its own custom identifier, populating index breaks. It looks for the specified identifier in the nested object too. This happens here, while it's recursively getting called

```php
    public function transform($object, array $fields)
    {
        $identifier = $this->propertyAccessor->getValue($object, $this->options['identifier']);
        $document = new Document($identifier);

```

How can this be solved?
Any help will be much appreciated

### PR DESCRIPTION
**Pull request by jvandesande**
This fixes #357

### CODE REVIEW

**Comment by jvandesande** [comment]
@merk @stof @XWB Is there someone who can review this PR?

**Comment by gnoesiboe** [comment]
+1

**Comment by djbfmeel** [comment]
+1

**Comment by evertharmeling** [comment]
+1

**Comment by Meuk** [comment]
+1

**Comment by merk** [comment]
There are no test cases to verify this fix. I need a failing test case on the original code to merge this PR.

**Comment by jvandesande** [comment]
@merk I've added the requested test cases

**Comment by XWB** [comment]
@jvandesande Can you fix this in 3.0 as well?

**Comment by jvandesande** [comment]
@XWB I can do that. When will this PR be checked/merged?

**Comment by jvandesande** [comment]
@XWB I've created a PR for the 3.0.x branch too: https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/935

**Comment by stof** [comment]
@XWB I suggest we stop maintaining multiple branches in parallel. It adds more work and should not be necessary if we really follow semver (see Twig for instance: it has 2 branches only because of the next major version being in progress)

**Comment by XWB** [comment]
@stof :+1: I'll prepare a final 3.0 release.

**Pull request merged**
