### PR TITLE
Support Symfony 7

### PR DESCRIPTION
**Pull request by evertharmeling**
Follow-up on #1933 to help move the SF 7 support forward.

- Fixed the CI errors
- Dropped support for Symfony `4.4`, as it complicated the deprecation of [MessageHandlerInterface](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Messenger/Handler/MessageHandlerInterface.php#L21) (and the attribute being available in `5.4`). Next to that [Symfony 4.4](https://symfony.com/releases#symfony-releases-calendar) isn't supported anymore at this moment.

### TODO
When [doctrine/phpcr-odm](https://github.com/doctrine/phpcr-odm) releases `2.0` version
  - [ ] Remove `"minimum-stability": "RC"` from `composer.json`
  - [ ] Update version `doctrine/phpcr-odm` to `^1.5.3 || ^2.0` in `composer.json`
  - [ ] Update version `jackalope/jackalope-doctrine-dbal` to `^1.2 || ^2.0` in `composer.json`

_PR could be merged in `master`, but the TODO's should be fixed in a new release of this bundle IMO._

### CODE REVIEW

**Comment by llupa** [comment]
@XWB 👀

**Review by XWB — APPROVED** [review]

**Comment by XWB** [comment]
:+1:

**Comment by XWB** [comment]
Thank you for all the hard work.

**Comment by evertharmeling** [comment]
Glad to be of help, thanks for the merge Karel!

**Comment by bastienho** [comment]
Thank you for this work.

When can we expect a release?

**Comment by trsteel88** [comment]
@XWB is this going to be released any time soon? Anything that can be done to help? Thanks.

**Pull request merged**
