### PR TITLE
allow symfony 5

### PR DESCRIPTION
**Pull request by Jeroeny**
#SymfonyHackday

### CODE REVIEW

**Comment by COil** [comment]
Hi @Jeroeny, thanks for the PR but the tests fail. It seems that in `tests/Functional/ProfilerTest.php`

``
twigLoaderFilesystem = new \Twig_Loader_Filesystem(__DIR__ . '/../../src/Resources/views/Collector');
``

`\Twig_Loader_Filesystem` should be replaced by `Twig\Loader\FilesystemLoader\FilesystemLoader`

**Comment by COil** [comment]
Hi @xabbuh , how are you? I saw you were in the FOS organization. Who could help us for this one? (review + merge) thanks. 🙂

**Comment by COil** [comment]
@Jeroeny  , made a PR on your branch.

**Comment by Jeroeny** [comment]
Thanks, lgtm so merged it.

**Comment by COil** [comment]
Still some warnings : 

1) FOS\ElasticaBundle\Tests\Functional\ProfilerTest::testRender with data set #0 (array(array(array())))

Class "Symfony\Bridge\Twig\Extension\HttpKernelRuntime" is declared "final" and cannot be mocked.

2) FOS\ElasticaBundle\Tests\Functional\ProfilerTest::testRender with data set #1 ('{"query":{"match_all":{}}}')

Class "Symfony\Bridge\Twig\Extension\HttpKernelRuntime" is declared "final" and cannot be mocked.

**Comment by COil** [comment]
@Jeroeny  can you revert my PR and rebase the master? Another was merged in the master, so the tests should be Ok now.

**Comment by Jeroeny** [comment]
Will do 👍

**Comment by COil** [comment]
@XWB  Seems Ok now. :)

**Comment by michellesanver** [comment]
Also remember to update travis, always forget it :)

**Comment by COil** [comment]
Hi @XWB , it is ok for you? 🙂

**Comment by COil** [comment]
Hi @lsmith77 , can it be merged please? :)

**Comment by COil** [comment]
Sorry @lsmith77  , I think the other PR regarding Symfony5 address all the problems at once.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1592

**Pull request closed without merging**
