### PR TITLE
Allow this bundle to work with symfony3

### PR DESCRIPTION
**Pull request by benji07**
https://github.com/KnpLabs/KnpPaginatorBundle/pull/346 should be merged before

### CODE REVIEW

**Comment by damienalexandre** [comment]
:+1:

**Comment by maximecolin** [comment]
:+1:

**Comment by merk** [comment]
Please dont bother pinging this issue until the mentioned PR is closed, it wont be merged until then.

**Comment by WouterJ** [comment]
@merk the mentioned PR is merged

**Pull request merged**
