### PR TITLE
Publish first beta version

### PR DESCRIPTION
**Pull request by deguif**

### CODE REVIEW

**Comment by deguif** [comment]
@XWB do you think a first beta can be published once your PR about removing public services is merged?

**Comment by XWB** [comment]
If I can figure out why the test keeps failing :)

**Comment by deguif** [comment]
Ready?

**Comment by XWB** [comment]
Perhaps we can address the remaining public services in the next beta? Would you be able to help?

**Comment by deguif** [comment]
@XWB yes, I will try my best.
I'm also discussing to help maintaining FOSOAuthServerBundle (https://github.com/FriendsOfSymfony/friendsofsymfony.github.io/issues/46#issuecomment-692465383)

**Comment by deguif** [comment]
I think we're more than ready for first beta release, and that we can keep working on breaking things before releasing the next stable major version later.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/releases/tag/v6.0.0-beta1

**Comment by deguif** [comment]
Thanks @XWB

**Comment by deguif** [comment]
Just a quick follow up, I deployed the first beta on production and all is fine ;)

**Pull request merged**
