### PR TITLE
Dispatch an event before transforming objects

### PR DESCRIPTION
**Pull request by tophsic**
As 9188566d introduce a post transform objects event, I need for a project a pre transform objects event.

### CODE REVIEW

**Comment by tophsic** [comment]
Do I need to edit Changelog-3.1 directly in the same commit?

**Comment by merk** [comment]
A few things:

- Please add an entry to the 3.2 Changelog (master is 3.2 and this is a new feature so it wont be merged into 3.1)
- Please add some documentation regarding this event

**Comment by tophsic** [comment]
I rebased the branch master, modify 3.2 changelog and did some documentation. Do you any suggestion?

Thanks

**Comment by hisie** [comment]
Are there any news about this issue?

**Comment by tophsic** [comment]
Just need to merge, isn'it ?

**Comment by XWB** [comment]
@tophsic Can you rebase one more time?

**Comment by tophsic** [comment]
Done

**Comment by XWB** [comment]
Thanks :+1:

**Pull request merged**
