### PR TITLE
Check that element have at least one value

### PR DESCRIPTION
**Pull request by biozshock**
According to https://github.com/symfony/symfony/issues/20356

### CODE REVIEW

**Comment by killerwolf** [comment]
`Using Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::cannotBeEmpty() at path "fos_elastica.clients..connections..http_error_codes" has no effect, consider requiresAtLeastOneElement() instead. In 4.0 both methods will behave the same.`

**Comment by XWB** [comment]
Thanks :)

**Comment by biozshock** [comment]
@XWB may we have a new tag?

**Comment by blackarcanis** [comment]
Not sure to understand how we can avoid this depreciation message...
I'm using the 5.1 version of ElasticaBundle on last 3.4 Symfony version and I would like to not have this depreciation message anymore. Anything I can do ?

**Comment by biozshock** [comment]
@blackarcanis Easy! This PR is not yet have a tag. Latest version 5.1.0 does not have it yet: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/v5.1.0/src/DependencyInjection/Configuration.php#L461
Just wait till new tag is released.

**Comment by blackarcanis** [comment]
@biozshock OK great, thank you ! :)

**Pull request merged**
