### PR TITLE
Clone $query  because size is set to 0 in ruflin package, causing 0 results

### PR DESCRIPTION
**Pull request by whoamicz**
$paginator = $finder->findPaginated($boolQuery);
$paginator->setMaxPerPage(25);
$paginator->setCurrentPage($page);

empty because in ruflin/elastica/lib/Elastica/Search.php is

$query = $this->getQuery();
$query->setSize(0);

### CODE REVIEW

**Comment by XWB** [comment]
I'd like to understand why Elastica is setting size to zero, ping @ruflin

**Comment by ruflin** [comment]
I assume this is related to https://github.com/ruflin/Elastica/issues/1261 ? BTW which version of Elastica is this?

**Comment by XWB** [comment]
@ruflin I looks to be the same issue indeed.

**Comment by XWB** [comment]
Fixed in https://github.com/ruflin/Elastica/pull/1264#event-1008219656

**Pull request closed without merging**
