### PR TITLE
split directory structure in doc, src and test

### PR DESCRIPTION
**Pull request by Tobion**
- for better clarity and better autoloading by excluding tests
- also with .gitattributes for optimized dist packages
- having docs and license in Resources/ is not recommended anymore

### CODE REVIEW

**Comment by XWB** [comment]
I like this change, good work @Tobion

**Comment by makasim** [comment]
I like it too! good work @Tobion

**Comment by Tobion** [comment]
Thanks guys. Ready to merge.

**Comment by Tobion** [comment]
Could I get write access so I can close some old issues? So I can do the release if you like.
I also think the branch 4.0.x should be changed to 4.x because features have been merged there. So the next 4.x release should be 4.1. So it's not a patch only branch anymore.

**Comment by makasim** [comment]
> So the next 4.x release should be 4.1. So it's not a patch only branch anymore.

that's the plan

**Comment by makasim** [comment]
> Could I get write access so I can close some old issues? I can do the release if you like.

ping @lsmith77

**Comment by lsmith77** [comment]
obviously fine for me (after all @Tobion is a co-worker of mine) .. @XWB fine for you too?

**Comment by XWB** [comment]
:+1:

**Comment by lsmith77** [comment]
done

**Pull request merged**
