### PR TITLE
Add PaginatorAdapterInterface as one of FantaPaginatorAdapter's interfaces

### PR DESCRIPTION
**Pull request by lemoinem**
Not having `PaginatorAdapterInterface` as one of `FantaPaginatorAdapter`'s interfaces kind of go against the purpose of having a `PaginatorAdapterInterface` in the first place...

### CODE REVIEW

**Comment by lemoinem** [comment]
Scrutinizer build says canceled. So I'm guessing it's related to the project's configuration and not to my modifications.

**Comment by XWB** [comment]
Thanks.

**Comment by ruudvanderweijde** [comment]
This results in a fatal error: https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1040

**Comment by lemoinem** [comment]
@steffenbrem Well, `PaginatorAdapterInterface` seems to be the base interface for the returned value from `FINDER->findPaginated()->getAdapter()`, which seems to be the only way to have both paginated results and access to the aggregations.

Did I miss something? The names of these interfaces and how they relate to each other seems a bit confusing...

**Pull request merged**
