### PR TITLE
Enable pagination of hybrid results

### PR DESCRIPTION
**Pull request by XWB**
Rebased version of https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/451

### CODE REVIEW

**Comment by nurikabe** [comment]
+1

**Comment by Airborn22** [comment]
+1

**Comment by respinoza** [comment]
+1

**Comment by jcrombez** [comment]
Maybe one of the others PR should be merged since this one have been going around for almost a year with no success ?

**Comment by piotrantosik** [comment]
any news?

**Comment by maximecolin** [comment]
Why this PR is not merged yet ? 

ping @merk

**Comment by gdbonino** [comment]
+1

**Comment by BlazingSun** [comment]
+1

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1111

**Pull request closed without merging**
