### PR TITLE
Use single option in setAllowedTypes

### PR DESCRIPTION
**Pull request by xurshid29**
Will be compatible  with the 3rd version of symfony .

### CODE REVIEW

**Comment by stloyd** [comment]
This is wrong, you should call `method_exits()` for new method, otherwise it's broken for Symfony `2.3`.

**Comment by xurshid29** [comment]
Ah, I see.

**Comment by xurshid29** [comment]
@stloyd I'll fix it.

**Comment by xurshid29** [comment]
@stloyd I don't think `method_exits()` can help here. `setAllowedTypes` in 2.3 version uses type hinting, which doesn't allow to pass a string.

**Comment by xurshid29** [comment]
I pushed the commit which fixes the 2.3 compatibility. The solution is not so pretty, but I couldn't find a better way.

**Comment by merk** [comment]
I removed the entire setAllowedTypes section to simplify this.

**Pull request closed without merging**
